config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'about', to: 'home#about'

  resources :books, only: %i[create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    return redirect_to @book, notice: t('.book_saved') if @book.save

    render :new
  end

  def show
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/new.html.erb
<h2>Novo livro</h2>
<%= render 'shared/errors', object: @book %>
<%= form_with model: @book do |form| %>
	<p><%= form.label :title , t('.title') %></p>
	<%= form.text_field :title %>
	<p><%= form.label :description , t('.description') %></p>
	<%= form.text_area :description %>
	<%= form.submit t('.save') %>
<% end %>

app/views/books/show.html.erb
<h2>Detalhes do livro</h2>

<%= @book.title %>
<%= @book.description %>

app/views/home/about.html.erb
<h2>Sobre</h2>
<p>Esse site serve...</p>

app/views/home/index.html.erb
<h2>Homepage</h2>
<p>meu nobre...</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<% object.errors.full_messages.each do |message| %>
		<p><%= message %></p>
	<% end %>
<% end %>

app/views/shared/_header.html.erb
<h1 id="title"><%= link_to t("system_title"), root_path %></h1>
<p>
	<%= link_to t(".home"), root_path %> | 
	<%= link_to t(".about"), about_path %> |
	<%= link_to t(".new"), new_book_path %>
</p>
<hr>

app/views/shared/_messages.html.erb
<% if notice %>
	<p><%= notice %></p>
<% end %>

<% if alert %>
	<p><%= alert %></p>
<% end %>